#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS="$ROOT/skills/deep-review/agents"
STACK="$ROOT/skills/deep-review/support/stack-profiler.md"

# Guard a few high-value factual/calibration statements that are easy to regress.
grep -q '24 by 24 CSS pixels' "$AGENTS/accessibility-scanner.md"
grep -q '44 by 44 CSS pixels' "$AGENTS/accessibility-scanner.md"
grep -q '2.5.7 Dragging Movements' "$AGENTS/accessibility-scanner.md"
grep -q 'React Compiler' "$AGENTS/react-reviewer.md"
grep -q 'never flag missing `React.memo`, `useMemo`, or `useCallback` by default' "$AGENTS/react-reviewer.md"
grep -q 'React Router' "$AGENTS/react-reviewer.md"
grep -q 'query key' "$AGENTS/react-reviewer.md"
grep -q 'server.allowedHosts: true' "$AGENTS/vite-reviewer.md"
grep -q 'Rolldown' "$AGENTS/vite-reviewer.md"
grep -q 'build.rolldownOptions' "$AGENTS/vite-reviewer.md"
grep -q 'deprecated compatibility alias' "$AGENTS/vite-reviewer.md"
grep -q 'barrel' "$AGENTS/vite-reviewer.md"
grep -q 'waitForTimeout' "$AGENTS/web-testing-reviewer.md"
grep -q 'Testing Library' "$AGENTS/web-testing-reviewer.md"
grep -q 'Vitest 5' "$AGENTS/web-testing-reviewer.md"
grep -q 'clearMocks' "$AGENTS/web-testing-reviewer.md"
grep -q 'ERR_PACKAGE_PATH_NOT_EXPORTED' "$AGENTS/js-package-reviewer.md"
grep -q 'peer' "$AGENTS/js-package-reviewer.md"
grep -q 'node_modules' "$AGENTS/js-package-reviewer.md"
grep -q 'exactOptionalPropertyTypes' "$AGENTS/ts-frontend-reviewer.md"
grep -q 'noUncheckedIndexedAccess' "$AGENTS/ts-frontend-reviewer.md"
grep -q 'noUncheckedSideEffectImports' "$AGENTS/ts-frontend-reviewer.md"
grep -q 'TypeScript 6.0' "$AGENTS/ts-frontend-reviewer.md"
grep -q 'native Node TypeScript' "$AGENTS/ts-backend-reviewer.md"
grep -q 'tsconfig.json' "$AGENTS/ts-backend-reviewer.md"
grep -q 'testing/synctest' "$AGENTS/go-reviewer.md"
grep -q 'generic methods' "$AGENTS/go-reviewer.md"
grep -q 'Go 1.27' "$AGENTS/go-reviewer.md"
grep -q 'unsafe_op_in_unsafe_fn' "$AGENTS/rust-reviewer.md"
grep -q 'TaskGroup' "$AGENTS/python-reviewer.md"
grep -q 'free-threaded' "$AGENTS/python-reviewer.md"
grep -q 'property hooks' "$AGENTS/php-reviewer.md"
grep -q 'asymmetric visibility' "$AGENTS/php-reviewer.md"

# Shared version context must carry the facts specialists depend on.
grep -q 'native Node TypeScript stripping' "$STACK"
grep -q 'Vite 8' "$STACK"
grep -q 'Vitest 5' "$STACK"
grep -q 'Go 1.27' "$STACK"
grep -q 'free-threaded CPython' "$STACK"

# Test-review calibration: protect the semantic rules and their false-positive guards.
grep -q 'mental-mutant check' "$AGENTS/test-analyzer.md"
grep -q 'Artificial-only' "$AGENTS/test-analyzer.md"
grep -q 'default/zero/empty/false' "$AGENTS/test-analyzer.md"
grep -q 'do not flag loops or parameterization by syntax alone' "$AGENTS/test-analyzer.md"
grep -q 'not to be discovered or run in the relevant pipeline' "$AGENTS/test-analyzer.md"
grep -q 'A test-smell label is not evidence' "$AGENTS/test-analyzer.md"

test -s "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Vercel Labs React Best Practices' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'React Router' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'TanStack Query' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Playwright' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Testing Library' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Vitest 5 announcement' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Node.js native TypeScript' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'TypeScript 6.0 release notes' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Vite 8 announcement' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'Go 1.27 release notes' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'free-threading support' "$ROOT/REVIEWER-SOURCES.md"
grep -q 'WCAG 2.2' "$ROOT/REVIEWER-SOURCES.md"

test -s "$ROOT/TEST-REVIEW-RESEARCH.md"
grep -q 'Fault sensitivity matters more than execution coverage' "$ROOT/TEST-REVIEW-RESEARCH.md"
grep -q 'Realism is a contract question' "$ROOT/TEST-REVIEW-RESEARCH.md"
grep -q 'Automated "test smell" labels need strong calibration' "$ROOT/TEST-REVIEW-RESEARCH.md"

echo "reviewer knowledge calibration smoke test passed"
